# CHANGE-TO-YOURNAME-aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  api:
    handler: index.app
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
